trigger:
  branches:
    include:
      - main

pr: none

pool:
  vmImage: ubuntu-latest

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      write-Host $(Build.DefinitionVersion)
      write-Host $(Build.SourceBranch)
      write-Host $(Build.SourceBranchName)
      write-Host $(Build.SourceVersion)
      write-Host $(Build.Repository.Name)
      write-Host $env:System.PullRequest.PullRequestNumber
- task: PowerShell@2
  env:
    GithubToken_ENV_VAR: $(GithubToken)
  enabled: false
  displayName: 'Automerge From $(FromBranch) to $(ToBranch) in Repo $(Repo)'
  inputs:
    filePath: '$(Build.SourcesDirectory)/autodelete.ps1'
    arguments: >-
      "$(Owner)"
      "$(Repo)"
      "$(TokenGithub)"
      # "$(FromBranch)"
      # "$(ToBranch)"
      # "$(PullRequestTitle)"
      # "$(Reviewers)"




# - task: CmdLine@2
#   inputs:
#     script: |
#       git config --global user.email "adinath.dukare@allscripts.com"
#       git config --global user.name "Adinath-Dukare-382"
#       git branch --merged | grep -v main | xargs git branch -D
      
