trigger:
  branches:
    include:
      - main
pr: none

variables:
 - group: sample
 - group: sample2

pool: 
  VMImage: ubuntu-latest

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      echo $(poh-v1)
      echo $(poh-V1)
  condition: and(succeeded(), eq( $(checktf) , 'true' ))

- task: PowerShell@2
  env:
    GithubToken_ENV_VAR: $(GithubToken)
  enabled: false
  displayName: 'Automerge From $(FromBranch) to $(ToBranch) in Repo $(Repo)'
  inputs:
    filePath: '$(Build.SourcesDirectory)/automerge.ps1'
    arguments: >-
      "$(Owner)"
      "$(Repo)"
      "$(FromBranch)"
      "$(ToBranch)"
      "$(PullRequestTitle)"
      "$(Reviewers)"
      
- task: PowerShell@2
  enabled: false
  env:
    GithubToken_ENV_VAR: $(GithubToken)
  displayName: 'Autodelete feature branch'
  inputs:
    filePath: '$(Build.SourcesDirectory)/AutoDelete.ps1'
    arguments: >-
      "$(Owner)"
      "$(Repo)"
      "$(Build.SourceVersion)"
      
  # condition: and(succeeded(), eq(variables['Build.Reason'], 'IndividualCI'))
