trigger: 
  branches:
    include:
      - main
pr:
 branches:
   include:
     - main

pool:
  vmImage: ubuntu-latest

steps:
- task: PowerShell@2
  env:
    GithubToken_ENV_VAR: $(GithubToken)
  enabled: True
  displayName: 'Automerge From $(FromBranch) to $(ToBranch) in Repo $(Repo)'
  inputs:
    filePath: '$(Build.SourcesDirectory)/autodelete.ps1'
    arguments: >-
      "$(Owner)"
      "$(Repo)"
      "$(TokenGithub)"
      # "$(FromBranch)"
      # "$(ToBranch)"
      # "$(PullRequestTitle)"
      # "$(Reviewers)"

# - task: CmdLine@2
#   inputs:
#     script: |
#       git config --global user.email "adinath.dukare@allscripts.com"
#       git config --global user.name "Adinath-Dukare-382"
#       git branch --merged | grep -v main | xargs git branch -D
      
