trigger:
  branches:
    include:
      - main
pr: none

pool:
  vmImage: ubuntu-latest

steps:
- task: PowerShell@2
  env:
    GithubToken_ENV_VAR: $(GithubToken)
  enabled: True
  displayName: 'Automerge From $(FromBranch) to $(ToBranch) in Repo $(Repo)'
  inputs:
    filePath: 'Build/Scripts/Utilities/AutoMergeBranch.ps1'
    arguments: >-
      "$(Owner)"
      "$(Repo)"
      "$(FromBranch)"
      "$(ToBranch)"
      "$(PullRequestTitle)"
      "$(Reviewers)"
