trigger: 
  branches:
    include:
      - main
pr: none

pool: SamplePool

steps:
- task: PowerShell@2
  env:
    GithubToken_ENV_VAR: $(GithubToken)
  enabled: false
  displayName: 'Automerge From $(FromBranch) to $(ToBranch) in Repo $(Repo)'
  inputs:
    filePath: '$(Build.SourcesDirectory)/automerge.ps1'
    arguments: >-
      "$(Owner)"
      "$(Repo)"
      "$(FromBranch)"
      "$(ToBranch)"
      "$(PullRequestTitle)"
      "$(Reviewers)"
      
- task: PowerShell@2
  env:
    GithubToken_ENV_VAR: $(GithubToken)
  enabled: true
  displayName: 'Autodelete feature branch'
  inputs:
    filePath: '$(Build.SourcesDirectory)/AutoDelete.ps1'
    arguments: >-
      "$(Owner)"
      "$(Repo)"
      "$(Build.SourceVersion)"
      
  # condition: and(succeeded(), eq(variables['Build.Reason'], 'IndividualCI'))
