trigger:
  branches:
    include:
      - main
pr: none

variables:
 - group: sample
 - group: sample2
 - name: azurefeed
   value: $(checktf)

parameters:
  - name: 'checktf'
    type: string
    default: true

pool: 
  VMImage: ubuntu-latest

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      echo $(poh-v1)
      echo $(poh-V1)
  condition: and(succeeded(), eq( variables['azurefeed'] , 'true' ))

- task: PowerShell@2
  env:
    GithubToken_ENV_VAR: $(GithubToken)
  enabled: false
  displayName: 'Automerge From $(FromBranch) to $(ToBranch) in Repo $(Repo)'
  inputs:
    filePath: '$(Build.SourcesDirectory)/automerge.ps1'
    arguments: >-
      "$(Owner)"
      "$(Repo)"
      "$(FromBranch)"
      "$(ToBranch)"
      "$(PullRequestTitle)"
      "$(Reviewers)"
      
- task: PowerShell@2
  enabled: false
  env:
    GithubToken_ENV_VAR: $(GithubToken)
  displayName: 'Autodelete feature branch'
  inputs:
    filePath: '$(Build.SourcesDirectory)/AutoDelete.ps1'
    arguments: >-
      "$(Owner)"
      "$(Repo)"
      "$(Build.SourceVersion)"
      
  # condition: and(succeeded(), eq(variables['Build.Reason'], 'IndividualCI'))

- task: NuGetAuthenticate@0
  inputs:
    nuGetServiceConnections: 'neworg_nuget'
  
- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg;$(Build.SourcesDirectory)/**/*/nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'neworg_nuget'
    
