trigger: 
  branches:
    include:
      - main
pr: none

pool:
  vmImage: ubuntu-latest

steps:
- task: PowerShell@2
  env:
    GithubToken_ENV_VAR: $(GithubToken)
  enabled: True
  displayName: 'Automerge From $(FromBranch) to $(ToBranch) in Repo $(Repo)'
  inputs:
    filePath: 'Build/Scripts/Utilities/AutoMergeBranch.ps1'
    arguments: >-
      "$(Owner)"
      "$(Repo)"
      "$(FromBranch)"
      "$(ToBranch)"
      "$(PullRequestTitle)"
      "$(Reviewers)"
      
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      write-Host $(Build.DefinitionVersion)
      write-Host $(Build.SourceBranch)
      write-Host $(Build.SourceBranchName)
      write-Host $(Build.SourceVersion)
      write-Host $(Build.SourceVersionMessage)
      write-Host $(Build.Repository.Name)
      write-Host $env:System.PullRequest.PullRequestNumber
      
- task: PowerShell@2
  env:
    GithubToken_ENV_VAR: $(GithubToken)
  enabled: true
  displayName: 'Automerge From $(FromBranch) to $(ToBranch) in Repo $(Repo)'
  inputs:
    filePath: '$(Build.SourcesDirectory)/auto.ps1'
    arguments: >-
      "$(Owner)"
      "$(Repo)"
      "$(Build.SourceVersion)"

