$source = "C:\Users\A888382\Desktop\Dustbin\zips\HIMReportDataSync"
$destination = "C:\Users\A888382\Desktop\Dustbin\zips\COPYFiles\"

xcopy "$source\appsettings.json" "$destination"  /c /d /i /y
xcopy "$source\microsoft.codeanalysis.csharp.dll" "$destination"  /c /d /i /y
xcopy "$source\appsettings.himreport.json"	"$destination"  /c /d /i /y
xcopy "$source\microsoft.codeanalysis.csharp.workspaces.dll"	"$destination"  /c /d /i /y
xcopy "$source\microsoft.codeanalysis.visualbasic.dll"	"$destination"  /c /d /i /y 
xcopy "$source\microsoft.codeanalysis.visualbasic.workspaces.dll"	"$destination"  /c /d /i /y
xcopy "$source\microsoft.codeanalysis.workspaces.dll"	"$destination"  /c /d /i /y
xcopy "$source\microsoft.reportviewer.common.deps.json"	"$destination"  /c /d /i /y
xcopy "$source\microsoft.reportviewer.common.dll"	"$destination"  /c /d /i /y
xcopy "$source\microsoft.reportviewer.datavisualization.deps.json"	"$destination"  /c /d /i /y
xcopy "$source\microsoft.reportviewer.datavisualization.dll"	"$destination"  /c /d /i /y 
xcopy "$source\microsoft.reportviewer.netcore.deps.json"	"$destination"  /c /d /i /y 
xcopy "$source\microsoft.reportviewer.netcore.dll"	"$destination"  /c /d /i /y 
xcopy "$source\microsoft.reportviewer.processingobjectmodel.deps.json"	"$destination"  /c /d /i /y 
xcopy "$source\microsoft.reportviewer.processingobjectmodel.dll"	"$destination"  /c /d /i /y 
xcopy "$source\postsharp.dll"	"$destination"  /c /d /i /y 
xcopy "$source\sni.dll"	"$destination"  /c /d /i /y 
xcopy "$source\sqlreportutilities.deps.json"	"$destination"  /c /d /i /y
xcopy "$source\sqlreportutilities.dll"	"$destination"  /c /d /i /y 
xcopy "$source\sxa.him.core.common.deps.json"	"$destination"  /c /d /i /y 
xcopy "$source\sxa.him.core.common.dll"	"$destination"  /c /d /i /y 
xcopy "$source\sxa.him.core.contracts.deps.json"	"$destination"  /c /d /i /y 
xcopy "$source\sxa.him.core.contracts.dll" "$destination"  /c /d /i /y 
xcopy "$source\sxa.him.core.dataaccess.deps.json"	"$destination"  /c /d /i /y 
xcopy "$source\sxa.him.core.dataaccess.dll"	"$destination"  /c /d /i /y 
xcopy "$source\sxa.him.core.report.business.deps.json"	"$destination"  /c /d /i /y 
xcopy "$source\sxa.him.core.report.business.dll"	"$destination"  /c /d /i /y 
xcopy "$source\sxa.him.core.report.generation.deps.json"	"$destination"  /c /d /i /y 
xcopy "$source\sxa.him.core.report.generation.dll"	"$destination"  /c /d /i /y 
xcopy "$source\sxa.him.core.report.opalintegration.deps.json"	"$destination"  /c /d /i /y 
xcopy "$source\sxa.him.core.report.opalintegration.dll"	"$destination"  /c /d /i /y 
xcopy "$source\sxa.him.core.report.service.deps.json"	"$destination"  /c /d /i /y 
xcopy "$source\sxa.him.core.report.service.dll"	"$destination"  /c /d /i /y 
xcopy "$source\system.codedom.dll"	"$destination"  /c /d /i /y 
xcopy "$source\system.composition.attributedmodel.dll"	"$destination"  /c /d /i /y 
xcopy "$source\system.composition.convention.dll"	"$destination"  /c /d /i /y 
xcopy "$source\system.composition.hosting.dll"	"$destination"  /c /d /i /y 
xcopy "$source\system.composition.runtime.dll"	"$destination"  /c /d /i /y 
xcopy "$source\system.composition.typedparts.dll"	"$destination"  /c /d /i /y 
xcopy "$source\system.data.oledb.dll"	"$destination"  /c /d /i /y 
xcopy "$source\system.data.sqlclient.dll"	"$destination"  /c /d /i /y 
xcopy "$source\system.io.packaging.dll"	"$destination"  /c /d /i /y 
xcopy "$source\system.management.dll"	"$destination"  /c /d /i /y 
xcopy "$source\system.resources.extensions.dll"	"$destination"  /c /d /i /y 
xcopy "$source\system.servicemodel.http.dll"	"$destination"  /c /d /i /y 
xcopy "$source\system.web.services.dll"	"$destination"  /c /d /i /y 
xcopy "$source\sr\microsoft.reportviewer.common.resources.dll"	"$destination"  /c /d /i /y 
xcopy "$source\sr\microsoft.reportviewer.datavisualization.resources.dll"	"$destination"  /c /d /i /y 
