name: CI

on:
  push:
    branches:
      - 'main'
    paths:
      - 'sample.json'
  pull_request:
    branches: 
      - main
      - feature_*
      - Feature_*
    types: [closed]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning' 
        type: string
  workflow_call:
#   schedule:
#     - cron:  '26 8 * * *'
#     - branches:
#         - release-22.2
  
env:
  IDNTenantID : "thinkpad"
  
jobs:
  Job:
      uses: ./.github/workflows/build.yml
      with:
          username1: ${env.IDNTenantID}
          username2: "$env:IDNTenantID"
          username3: $env.USER
          username4: ${IDNTenantID}
      secrets:
          RELAME: ${{ secrets.RELAME }}
      
#   Job2:
#       uses: ./.github/workflows/build.yml
#       with:
#           username1: "adinath"
#           username2: "dukare"
#           username3: "realme"
#       secrets:
#           RELAME: ${{ secrets.RELAME }}
          
#   HWS_workflow:
#       needs: [ HC_workflow ]
#       uses: ./.github/workflows/test2.yml
#       with:
#           username1: "adinath"
#           username2: ${{ needs.example_job1.outputs.DBServer1 }}
