name: CI

on:
  pull_request:
    branches: 
      - main
      - feature_*
      - Feature_*
    types: [closed]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning' 
        type: string
  workflow_call:
jobs:
  Job:
      uses: ./.github/workflows/build.yml
      with:
          username1: "adinath"
          username2: "dukare"
      secrets:
          token: ${{ secrets.AUTODELETE_GITHUB_TOKEN }}
          
#   HWS_workflow:
#       needs: [ HC_workflow ]
#       uses: ./.github/workflows/test2.yml
#       with:
#           username1: "adinath"
#           username2: ${{ needs.example_job1.outputs.DBServer1 }}
