name: CI

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning' 
        type: string
  workflow_call:
jobs:
  HC_workflow:
      uses: ./.github/workflows/test.yml
      with:
          username1: "adinath"
          username2: "dukare"
          
  HWS_workflow:
      needs: [ HC_workflow ]
      uses: ./.github/workflows/test.yml
      with:
          username1: "adinath"
          username2: "dukare"
