name: Reusable workflow example

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning' 
        type: string
  workflow_call:
    inputs:
      username1:
        required: true
        type: string
      username2:
        required: true
        type: string

jobs:
  example_job:
    runs-on: self-hosted
    steps:
      - run: echo ${{ inputs.username2 }}
      - run: echo "The job was triggered by a ${{ github.event_name }} event."
      - run: echo ${{ needs.example_job.outputs.DBServer1 }}
      - run: |
          echo "Adinath"
          echo "Dukare"
