name: Reusable workflow example

on:
  workflow_call:
    inputs:
      username1:
        required: true
        type: string
      username2:
        required: true
        type: string

jobs:
  example_job:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.username1 }}
