name: Reusable workflow example

on:
  workflow_call:
    inputs:
      username1:
        required: true
        type: string
      username2:
        required: true
        type: string
      username3:
        required: true
        type: string
        default: lenovo

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.username3 }}
