# This is a basic workflow to help you get started with Actions

name: test

# Controls when the workflow will run
on:
  workflow_dispatch:
  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single jobcalled "build"
  build:
    # The type of runner that the job will run on
    runs-on: testingrunner

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo testing

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        if: ${{ false }}
        run: |
          echo testing purpose

      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v3 
        with:
         token: ${{ secrets.github_token }}
         prefix: client
         
      - name : Get KeyValut Values 
        shell: pwsh          
        run: |   
             $xmlfile = [xml](gc -Path "test.config")
             $xmlfile
             write-host "hellooo"
             $connectionstring = $xmlfile.configuration.idntenantasinfo.add.apohtenantid
             write-host "hellooo world"
             write-host $connectionstring
             write-host "hellooo"
             $xmlfile.configuration.idntenantasinfo.add.POHTenantId = "adinath"
