name: Workflow Notifications

on:
  workflow_run:
    workflows: [ "CI", "testing-poh-873a229c-4bc2-4efc-9fb1-2671c36721e5-entsvr-testing-ausnsjagcx" ]

jobs:
  notifications:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: octogeeks/send-workflow-notifications@v1
      with:
        configuration: ./.github/workflow-notifications.yml
